### ISSUE TITLE
Possible incompatibility with WebStorm 10

### ISSUE THREAD

**Issue by denofevil** [idok/react-templates-plugin#3]
Hi,

I'm Dennis from WebStorm team. Our internal check indicated that your plugin v1.0.12 is using API that is not compatible with upcoming v10 EAP:

```
com.intellij.lang.javascript.index.JSIndexEntry com.intellij.lang.javascript.index.JavaScriptIndex#getEntryForFile(VirtualFile, GlobalSearchScope)
com.intellij.lang.javascript.index.CompositeIndexContent com.intellij.lang.javascript.index.JSSymbolUtil#indexFile(PsiFile, com.intellij.util.indexing.FileContent)
com.intellij.lang.javascript.index.JSIndexEntry
com.intellij.lang.javascript.index.JSEntryIndex
```

As I don't see these calls in the repository (as well as v1.0.12), I suppose they're not yet pushed. Please contact me to receive WS10 nightly build and API migration advice if you want to adopt your plugin early.

**Comment by idok** [comment]
I've cleaned up unused code, can you please check again?
Thanks

**Comment by denofevil** [comment]
It seems ok now, thank you!
