### ISSUE TITLE
Contributors Documentation

### ISSUE THREAD

**Issue by bgrieder** [idok/react-templates-plugin#5]
Hi,

I would like to add better support for Typescript in the plugin however I have been unable to get the plugin to compile in IntelliJ (missing classes, etc...).
Could you please add some instruction details on how to set-up the dev environment in IntelliJ starting from the GitHub repo ?
Also, maybe you could commit the `. idea` directory with the exception of `workspace.xml` file as a help ?

Thanks

**Comment by idok** [comment]
I've updated the docs and hopefully you will be able to compile.
It's not recommended to push .idea to git so I hope you could do it without it.
Tell me if you need help.

**Comment by bgrieder** [comment]
I had a couple of issues to get going on 14.0.3:

1- IntelliJ does not import plugins well: I had to manually hack the react-templates-plugin.iml file to tell that it is not a java module but a plugin.
My current content is 

<?xml version="1.0" encoding="UTF-8"?>
<module type="PLUGIN_MODULE" version="4">
<component name="DevKit.ModuleBuildProperties" url="file://$MODULE_DIR$/META-INF/plugin.xml" />
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/resources" type="java-resource" />
    </content>
    <orderEntry type="jdk" jdkName="IDEA IU-139.1117.1" jdkType="IDEA JDK" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="src" level="project" />
    <orderEntry type="module" module-name="intellij-common1" />
  </component>
</module>
Maybe you should consider committing this file at leat

2- I had to add jars to the IDEA JDK from my Utlimate installation at plugins/JavascriptLanguage/lib. I picked all of them but resources_en.jar. Maybe I do not need all of these

Since this is a plugin that can run in IntelliJ idea only, a few files from .idea may help

3- I had to comment out the completion.contributor in plugin.xml because the class com.wix.rt.codeInsight.PropertyCompletionContributor is not available in the sources. Could you please check ?

<completion.contributor language="HTML" implementationClass="com.wix.rt.codeInsight.PropertyCompletionContributor"/>

Thanks.

b.
