### ISSUE TITLE
Don't accept nodejs PATH

### ISSUE THREAD

**Issue by LOQUILLO** [idok/react-templates-plugin#8]
Don't accept the default path for Nodejs, and it's in my main PATH.
I see this message: Path to node interpreter is invalid Fix it
My specs is Windows 7 x64 Ultimate
WebStorm 10.0.1
![error_rt](https://cloud.githubusercontent.com/assets/1308190/7014681/8e970bf6-dc8d-11e4-97df-9da2112b63fb.png)

**Comment by idok** [comment]
Hi,
Sorry for the delayed response.
What do get when you press on the arrow button in the Node combo box?
